### ISSUE TITLE
Cannot receive multiple messages

### ISSUE THREAD

**Issue by MattCollins84** [jhs/cqs#10]
I am trying to pull multiple items from a queue, but i only ever receive one item...

my code:
cqs.ReceiveMessage('queue_name', 3, function(er, messages) {
  console.log(messages);
});

always shows one item, no matter how long I leave it, or how many items are in the queue (1, 2 or 3).

Is this a bug or am I misunderstanding something?

**Comment by jhs** [comment]
Hi, Matt. If I recall, CQS should support receiving from 1 to 10 messages.

I think I may have a bug in queue.js, `receive_message()`. What happens if you do it this way?

```
cqs.ReceiveMessage({'queue':'queue_name', 'MaxNumberOfMessages':3}, function(er, messages) {
  console.dir(messages) // Or whatever
})
```

Thanks. I am not sure if that code will trigger the bug, however I am very suspicious of line 460 in my code. It looks like I should assign to `queue` there, not `Queue`.

**Comment by MattCollins84** [comment]
Hi, thanks for replying - weirdly, this just started working properly! I'm not sure what happened, but i'll close this issue for now and investigate what you have mentioned above.

Thanks!
